### ISSUE TITLE
selection contrast on sidebar 

### ISSUE THREAD

**Issue by vitormalencar** [vitormalencar/sourc#3]
when some file is selected the black text makes hard to read 

![Screen Shot 2020-04-20 at 10 50 46](https://user-images.githubusercontent.com/7741167/79733049-d37c6f00-82f4-11ea-8efe-34e8e6c18a14.png)

**Comment by saralonngren** [comment]
It's hard to read when the file is selected and you put your mouse on top of it.

![Captura de tela de 2020-04-20 11-12-38](https://user-images.githubusercontent.com/10124552/79761645-1a1f9880-82f8-11ea-9bdd-f48d39b58ab6.png)

**Comment by janderson-souza** [comment]
I felt the same difficulty. maybe using '# ff85ef' as a background for the selected file helps

**Comment by vitormalencar** [comment]
how about

![Screen Shot 2020-04-20 at 16 55 23](https://user-images.githubusercontent.com/7741167/79766044-bf059a00-8327-11ea-8463-64e9683933ec.png)

**Comment by janderson-souza** [comment]
i liked

**Comment by vitormalencar** [comment]
the latest release should solve this problem 
@janderson-souza  @saralonngren please let me know if is all good  https://github.com/vitormalencar/sourc/releases/tag/v0.0.6
